name: test-workflow
on:
  pull_request:
    branches: [main]
jobs:
  test-workflow:
    #if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' }}
    runs-on: ubuntu-latest
    steps:
      - name: Show properties
        run: |
          echo ${{ github.event.action }}
